version: '3'
services:
  db:
    build: .
    image: db
    ports:
      - "[ex_port]:3306"
    volumes:
      - ./data:/var/lib/mysql
    tty: true
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 100s
      retries: 6
