version: '3'
services:
  db:
    build: .
    image: db
    ports:
      - "2014:3306"
    networks:
      - network
    volumes:
      - ./data:/var/lib/mysql
    tty: true
    restart: always
    healthcheck:
      test: ["CMD", "echo", "ok"]
      interval: 10s
      timeout: 100s
      retries: 6

networks:
  network:
    driver: bridge